baseURL = 'https://blog.oskr.one'
title = "Oscar's Vault"
theme = 'papermod'
languageCode = 'en-us'
copyright = "© [MoXcz](https://github.com/moxcz)"

enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentsUseClasses = true
mainsections = ["notes"]

[minify]
disableXML = true

[pagination]
disableAliases = false
pagerSize = 5

[languages]

[languages.en]
languageName = "English"
weight = 1

[languages.en.taxonomies]
tag = "tags"

[[languages.en.menu.main]]
name = "Notes"
url = "notes"
weight = 4

[[languages.en.menu.main]]
name = "Archive"
url = "archives"
weight = 5

[[languages.en.menu.main]]
name = "Search"
url = "search/"
weight = 10

[[languages.en.menu.main]]
name = "Tags"
url = "tags/"
weight = 10

# [languages.es]
# languageName = ":es:"
# weight = 2
# title = ""
#
# [languages.es.taxonomies]
# tag = "Tags"
#
# [[languages.es.menu.main]]
# name = "Archive"
# url = "archives/"
# weight = 5
#
# [[languages.es.menu.main]]
# name = "Tags"
# url = "tags"
# weight = 10
#
# [languages.es.params]
# languageAltTitle = "Spanish"

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
env = "production"
description = "public vault"
author = "Oscar"
defaultTheme = "auto"
ShowShareButtons = false
ShowReadingTime = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
ShowAllPagesInArchive = true
ShowPageNums = true
ShowToc = true
images = [""]

[params.homeInfoParams]
Title = 'Home'
Content = """
Welcome to my public knowledge base.

These notes come from my personal vault, feel free to use the search or tags to explore.
"""

[[params.socialIcons]]
name = "github"
title = "View Source on Github"
url = "https://github.com/moxcz/vault"

[params.editPost]
URL = "https://github.com/moxcz/moxcz/tree/main/site/content"
Text = "Suggest Changes"
appendFilePath = true

[params.assets]
disableHLJS = true

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[services.instagram]
disableInlineCSS = true

[services.x]
disableInlineCSS = true
