server {
  listen 80;
  server_name _;
  access_log /var/log/nginx/host.access.log main;
  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ $uri.html =404;
  }

  location /blog {
    try_files $uri $uri/ $uri.html =404;
  }

  location /images {
    try_files /blog$uri =404;
  }

  error_page 404 /404.html;
  location = /404.html {
    internal;
  }

  location ~ ^/(favicon\.ico|favicon\.svg|favicon-96x96\.png|apple-touch-icon\.png|site\.webmanifest|web-app-manifest-192x192\.png|web-app-manifest-512x512\.png)$ {
    try_files /blog$uri =404;
    access_log off;
  }
}
